In [7]:
import pandas as pd
import numpy as np

data1 = pd.read_csv('data_merge1.csv', index_col=0)
data2 = pd.read_csv('eunmin.csv', index_col=0)
data3 = pd.read_csv('sydf.csv', index_col=0)
data4 = pd.read_csv('출생_혼인_주택.csv', index_col=0)

In [8]:
frame = [data1, data2, data3, data4]
result = pd.concat(frame, axis=1)
result

,대출일반,대출주택,졸업자수,사교육비,인구,자가용,직장가입자,지역가입자,사회단체참여율,수출,...,사망자수,신혼부부수(합계),초혼부부 평균 출산자녀수,맞벌이 부부 수,주택소유 신혼부부 수,실업률,1인가구 비율,출생아수(명),혼인건수(건),주택매매가격동향
2000,NaN,NaN,NaN,NaN,47008111.0,NaN,NaN,NaN,NaN,172267511.0,...,248740.0,NaN,NaN,NaN,NaN,4.4,NaN,NaN,NaN,NaN
2001,NaN,NaN,NaN,NaN,47370164.0,NaN,NaN,NaN,NaN,150439144.0,...,243813.0,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN
2002,NaN,NaN,NaN,NaN,47644736.0,NaN,NaN,NaN,NaN,162470528.0,...,247524.0,NaN,NaN,NaN,NaN,3.3,NaN,NaN,NaN,NaN
2003,NaN,NaN,NaN,NaN,47892330.0,NaN,NaN,NaN,44.8,193817443.0,...,246463.0,NaN,NaN,NaN,NaN,3.6,NaN,NaN,NaN,NaN
2004,NaN,NaN,NaN,NaN,48082519.0,NaN,NaN,NaN,NaN,253844672.0,...,246220.0,NaN,NaN,NaN,NaN,3.7,NaN,NaN,NaN,NaN
2005,NaN,NaN,NaN,NaN,48184561.0,NaN,NaN,NaN,NaN,284418743.0,...,245874.0,NaN,NaN,NaN,NaN,3.7,NaN,NaN,NaN,NaN
2006,NaN,NaN,NaN,NaN,48438292.0,NaN,NaN,NaN,38.8,325464848.0,...,244162.0,NaN,NaN,NaN,NaN,3.5,NaN,NaN,NaN,NaN
2007,NaN,NaN,NaN,200400.0,48683638.0,NaN,NaN,NaN,NaN,371489086.0,...,246482.0,NaN,NaN,NaN,NaN,3.2,NaN,NaN,NaN,NaN
2008,NaN,NaN,NaN,209095.0,49054708.0,NaN,NaN,NaN,NaN,422007328.0,...,246113.0,NaN,NaN,NaN,NaN,3.2,NaN,NaN,NaN,NaN
2009,NaN,NaN,NaN,216259.0,49307835.0,NaN,75391264.0,27525025.0,39.8,363533561.0,...,246942.0,NaN,NaN,NaN,NaN,3.6,NaN,NaN,NaN,NaN
2010,NaN,NaN,NaN,208718.0,49554112.0,NaN,88694835.0,30519406.0,NaN,466383762.0,...,255405.0,NaN,NaN,NaN,NaN,3.7,NaN,470171.0,326104.0,1.9
2011,8.75,13.50,558932.0,201266.0,49936638.0,NaN,125900203.0,40538413.0,46.6,555213656.0,...,257396.0,NaN,NaN,NaN,NaN,3.4,NaN,471265.0,329087.0,6.9
2012,4.75,3.75,566324.0,190395.0,50199853.0,NaN,160836393.0,49573644.0,NaN,547869792.0,...,267221.0,NaN,NaN,NaN,NaN,3.2,NaN,484550.0,327073.0,0.0
2013,3.00,6.50,555142.0,185960.0,50428893.0,NaN,184333563.0,53303425.0,50.1,559632434.0,...,266257.0,NaN,NaN,NaN,NaN,3.1,NaN,436455.0,322807.0,0.3
2014,7.00,23.50,557234.0,182297.0,50746659.0,NaN,183622983.0,51096341.0,NaN,572664607.0,...,267692.0,NaN,NaN,NaN,NaN,3.5,NaN,435435.0,305507.0,1.7
2015,6.75,30.25,576023.0,178346.0,51014947.0,19622569.0,181165551.0,48949590.0,48.9,526756503.0,...,275895.0,1471647.0,0.82,595850.0,640709.0,3.6,27.4,438420.0,302828.0,3.5
2016,3.50,9.75,580695.0,180606.0,51217803.0,20345309.0,169794557.0,45567250.0,NaN,495425940.0,...,280827.0,1436948.0,0.80,603281.0,633642.0,3.7,28.1,406243.0,281635.0,0.7
2017,13.50,5.25,574009.0,186703.0,51361911.0,20984258.0,NaN,NaN,49.7,573694421.0,...,285534.0,1379766.0,0.78,585957.0,616621.0,3.7,28.7,357771.0,264455.0,1.5
2018,3.50,-4.25,NaN,194852.0,51606633.0,21539573.0,NaN,NaN,NaN,604859657.0,...,298820.0,1322406.0,0.74,594409.0,594721.0,3.8,29.2,326822.0,257622.0,1.1
2019,7.50,-2.25,NaN,NaN,NaN,21908362.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
result.shape

(20, 38)

In [14]:
result.to_csv('total_merge_data.csv', index=True)